### ISSUE TITLE
Criar tela de detalhes de cursos

### ISSUE THREAD

**Issue by fgpetter** [fgpetter/redemetrologica#58]
Criar tela de detalhes de curso
Usar como referencia: https://redemetrologica.com.br/curso-detalhe/?codcurso=2031

Na tela irá carregar os dados do agendamento de curso no topo

![Image](https://github.com/fgpetter/redemetrologica/assets/47160748/691aad14-7c6a-4f4c-8143-30ee36e2c599)

Na parte inferior os detalhes do curso

Botão de inscrever-se e preço só será visível se inscricoes = true

**Comment by Krausz90** [comment]
![Image](https://github.com/fgpetter/redemetrologica/assets/136640119/f122ff76-fde7-4b83-a753-1e894fe32bb2)



![Image](https://github.com/fgpetter/redemetrologica/assets/136640119/9b62f95a-a2fc-49f6-a2e3-62041cf8ea47)



![Image](https://github.com/fgpetter/redemetrologica/assets/136640119/7a679653-5d3b-4690-9378-49ae1ac56917)
