### ISSUE TITLE
Adicionar alerta de confirmação de deleção

### ISSUE THREAD

**Issue by fgpetter** [fgpetter/redemetrologica#67]
Quando o cliente clicar em deletar em um item da tabela, deve aparecer um alerta confirmando a deleção

Links para exemplos e documentação
https://sweetalert2.github.io/#usage
http://steex.laravel.themesbrand.com/advance-ui-sweetalerts

**Comment by Krausz90** [comment]
FEATURE/SWEETALERT-67

**Comment by Krausz90** [comment]
<li>
                                              <x-painel.form.delete route="post-delete" id="{{ $post->id }}" />
                                          </li>
